# Generated by Django 4.1.1 on 2022-11-26 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 14, 14, 36, 623397, tzinfo=datetime.timezone.utc)),
        ),
    ]
