# Generated by Django 4.1.1 on 2022-11-27 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_date_alter_post_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 22, 18, 49, 702706, tzinfo=datetime.timezone.utc)),
        ),
    ]
