# Generated by Django 4.1.1 on 2022-11-25 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_date_alter_userfollowing_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 4, 45, 50, 601680, tzinfo=datetime.timezone.utc)),
        ),
    ]
